# Practice Day 2

##### Restaurant tips — 
##### cleaning & new columns
##### Q1 Load restaurant.csv. Check for nulls and duplicates. Report your findings.
##### Q2 Add a tip_pct column: tip as a percentage of total_bill. Round to 2 decimals.
##### Q3 Add a tip_category column: "Low" if tip_pct < 10%, "Medium" if 10–20%, "High" if > 20%. Use np.select().
##### Q4 Add a bill_per_person column = total_bill / size. Round to 2 decimals.
##### Q5 Filter for weekend dinners (day is Sat or Sun, time is Dinner) with a party size >= 3.

In [34]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\user\Desktop\Python1\DataSample\restaurant.csv")
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [48]:
# Q1 Load restaurant.csv. Check for nulls and duplicates. Report your findings.
print('Nulls:\n',df.isna().sum()) # count na 
print('\nDuplicates count:',df.duplicated().sum()) # count duplicates
print('\nDuplicates:\n',df[df.duplicated()]) # pull out duplicates

Nulls:
 total_bill         0
tip                0
sex                0
smoker             0
day                0
time               0
size               0
tip_pct            0
tip_category       0
bill_per_person    0
dtype: int64

Duplicates count: 1

Duplicates:
      total_bill  tip     sex smoker   day   time  size  tip_pct tip_category  \
202        13.0  2.0  Female    Yes  Thur  Lunch     2    15.38       Medium

     bill_per_person
202              6.5

In [50]:
# Q2 Add a tip_pct column: tip as a percentage of total_bill. Round to 2 decimals.
df['tip_pct'] = (df['tip']/df['total_bill']*100).round(2)
df.head()

,total_bill,tip,sex,smoker,day,time,size,tip_pct,tip_category,bill_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,5.94,Low,8.49
1,10.34,1.66,Male,No,Sun,Dinner,3,16.05,Medium,3.45
2,21.01,3.50,Male,No,Sun,Dinner,3,16.66,Medium,7.00
3,23.68,3.31,Male,No,Sun,Dinner,2,13.98,Medium,11.84
4,24.59,3.61,Female,No,Sun,Dinner,4,14.68,Medium,6.15

In [37]:
# Q3 Add a tip_category column: "Low" if tip_pct < 10%, "Medium" if 10–20%, "High" if > 20%. Use np.select().
conditions = [
df['tip_pct'] < 10,
df['tip_pct'] <= 20,
df['tip_pct'] > 20 
] 
choices = ['Low', 'Medium', 'High']
df['tip_category'] = np.select(conditions, choices, default = 'Unknown')
df.head()

   total_bill   tip     sex smoker  day    time  size  tip_pct tip_category
0       16.99  1.01  Female     No  Sun  Dinner     2     5.94          Low
1       10.34  1.66    Male     No  Sun  Dinner     3    16.05       Medium
2       21.01  3.50    Male     No  Sun  Dinner     3    16.66       Medium
3       23.68  3.31    Male     No  Sun  Dinner     2    13.98       Medium
4       24.59  3.61  Female     No  Sun  Dinner     4    14.68       Medium

In [39]:
# Q4 Add a bill_per_person column = total_bill / size. Round to 2 decimals.
df['bill_per_person'] = round(df['total_bill'] / df['size'],2)
df.head()

,total_bill,tip,sex,smoker,day,time,size,tip_pct,tip_category,bill_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,5.94,Low,8.49
1,10.34,1.66,Male,No,Sun,Dinner,3,16.05,Medium,3.45
2,21.01,3.50,Male,No,Sun,Dinner,3,16.66,Medium,7.00
3,23.68,3.31,Male,No,Sun,Dinner,2,13.98,Medium,11.84
4,24.59,3.61,Female,No,Sun,Dinner,4,14.68,Medium,6.15

In [44]:
# Q5 Filter for weekend dinners (day is Sat or Sun, time is Dinner) with a party size >= 3.
df[(df['day'].isin(['Sat','Sun'])) & (df['time']== 'Dinner') & (df['size']>=3)]

,total_bill,tip,sex,smoker,day,time,size,tip_pct,tip_category,bill_per_person
1,10.34,1.66,Male,No,Sun,Dinner,3,16.05,Medium,3.45
2,21.01,3.50,Male,No,Sun,Dinner,3,16.66,Medium,7.00
4,24.59,3.61,Female,No,Sun,Dinner,4,14.68,Medium,6.15
5,25.29,4.71,Male,No,Sun,Dinner,4,18.62,Medium,6.32
7,26.88,3.12,Male,No,Sun,Dinner,4,11.61,Medium,6.72
...,...,...,...,...,...,...,...,...,...,...
227,20.45,3.00,Male,No,Sat,Dinner,4,14.67,Medium,5.11
230,24.01,2.00,Male,Yes,Sat,Dinner,4,8.33,Low,6.00
231,15.69,3.00,Male,Yes,Sat,Dinner,3,19.12,Medium,5.23
238,35.83,4.67,Female,No,Sat,Dinner,3,13.03,Medium,11.94
239,29.03,5.92,Male,No,Sat,Dinner,3,20.39,High,9.68

In [46]:
# Q5 Filter for weekend dinners (day is Sat or Sun, time is Dinner) with a party size >= 3. USE QUERY
df.query("day in ['Sat','Sun'] and time == 'Dinner' and size >= 3")

,total_bill,tip,sex,smoker,day,time,size,tip_pct,tip_category,bill_per_person
1,10.34,1.66,Male,No,Sun,Dinner,3,16.05,Medium,3.45
2,21.01,3.50,Male,No,Sun,Dinner,3,16.66,Medium,7.00
4,24.59,3.61,Female,No,Sun,Dinner,4,14.68,Medium,6.15
5,25.29,4.71,Male,No,Sun,Dinner,4,18.62,Medium,6.32
7,26.88,3.12,Male,No,Sun,Dinner,4,11.61,Medium,6.72
...,...,...,...,...,...,...,...,...,...,...
227,20.45,3.00,Male,No,Sat,Dinner,4,14.67,Medium,5.11
230,24.01,2.00,Male,Yes,Sat,Dinner,4,8.33,Low,6.00
231,15.69,3.00,Male,Yes,Sat,Dinner,3,19.12,Medium,5.23
238,35.83,4.67,Female,No,Sat,Dinner,3,13.03,Medium,11.94
239,29.03,5.92,Male,No,Sat,Dinner,3,20.39,High,9.68