# Practice Day 7

##### Restaurant + time lookup — multi-table joins & reshaping
##### Multi-table joins, pivot, string ops, category analysis
##### Q1 Load time_hours.xlsx and JOIN it to restaurant.csv on the time column. Add the hour range to each restaurant row.
##### Q2 Create a pivot table: rows = day, columns = time (Lunch/Dinner), values = average total_bill.
##### Q3 Group by smoker and sex. Calculate count of visits, average tip_pct, and average bill_per_person.
##### Q4 Which day + time combination generates the highest total revenue (sum of total_bill)? Show a ranked summary table.
##### Q5 Find days where the average tip percentage is below 15% (HAVING equivalent). What pattern do you notice?

In [29]:
import pandas as pd
import numpy as np
df_rest=pd.read_csv(r"C:\Users\user\Desktop\Python1\DataSample\restaurant.csv")
df_time=pd.read_excel(r"C:\Users\user\Desktop\Python1\DataSample\time_hours.xlsx")
print(df_rest.head())
print(df_time.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
     time    hour
0  Dinner  19-21h
1   Lunch  10-12h

In [30]:
# Q1 Load time_hours.xlsx and JOIN it to restaurant.csv on the time column. Add the hour range to each restaurant row.

In [31]:
df_q1 = pd.merge(df_rest, df_time, on = 'time')
df_q1.head()

   total_bill   tip     sex smoker  day    time  size    hour
0       16.99  1.01  Female     No  Sun  Dinner     2  19-21h
1       10.34  1.66    Male     No  Sun  Dinner     3  19-21h
2       21.01  3.50    Male     No  Sun  Dinner     3  19-21h
3       23.68  3.31    Male     No  Sun  Dinner     2  19-21h
4       24.59  3.61  Female     No  Sun  Dinner     4  19-21h

In [32]:
# Q2 Create a pivot table: rows = day, columns = time (Lunch/Dinner), values = average total_bill.

In [33]:
pd.pivot_table(
    data = df_q1,
    index = 'day',
    columns = 'time',
    values = 'total_bill',
    aggfunc = 'mean' 
)

time     Dinner      Lunch
day
Fri   19.663333  12.845714
Sat   20.441379        NaN
Sun   21.410000        NaN
Thur  18.780000  17.664754

In [34]:
# Q3 Group by smoker and sex. Calculate count of visits, average tip_pct, and average bill_per_person.

In [60]:
df_q1['tip_pct'] = df_q1['tip'] / df_q1['total_bill']*100
df_q1['bill_per_person'] = df_q1['total_bill'] / df_q1['size']

In [61]:
df_q1.groupby(['smoker','sex']).agg(
    count_of_visits = ('total_bill','count'),
    average_tip_pct = ('tip_pct','mean'),
    average_bill_per_person = ('bill_per_person','mean')
).round(2)

               count_of_visits  average_tip_pct  average_bill_per_person
smoker sex
No     Female               54            15.69                     7.24
       Male                 97            16.07                     7.43
Yes    Female               33            18.22                     7.83
       Male                 60            15.28                     9.24

In [ ]:
# Q4 Which day + time combination generates the highest total revenue (sum of total_bill)? Show a ranked summary table.
df_q4 = df_q1.groupby(['day','time'])['total_bill'].sum().reset_index()
df_q4['rank'] = df_q4['total_bill'].rank(method = 'min', ascending = False).astype(int)
df_q4.sort_values('rank')

# Sat Dinner generates the highest total revenue

    day    time  total_bill  rank
2   Sat  Dinner     1778.40     1
3   Sun  Dinner     1627.16     2
5  Thur   Lunch     1077.55     3
0   Fri  Dinner      235.96     4
1   Fri   Lunch       89.92     5
4  Thur  Dinner       18.78     6

In [ ]:
# Q5 Find days where the average tip percentage is below 15% (HAVING equivalent). What pattern do you notice?

In [75]:
avg_tip = df_q1.groupby(['day','time'])['tip_pct'].mean()
avg_tip[avg_tip>15]
# Sat generates the most revenue but the least tip... ppl tend to tip less on bigger bills?

day   time
Fri   Dinner    15.891611
      Lunch     18.876489
Sat   Dinner    15.315172
Sun   Dinner    16.689729
Thur  Dinner    15.974441
      Lunch     16.130074
Name: tip_pct, dtype: float64

In [ ]:
now = pd.Timestamp.now()

In [81]:
type(now)

pandas._libs.tslibs.timestamps.Timestamp

In [82]:
today = pd.to_datetime(now)

In [83]:
type(today)

pandas._libs.tslibs.timestamps.Timestamp

In [84]:
today

Timestamp('2026-03-26 20:32:43.210994')

In [90]:
today + pd.to_timedelta( 5, unit = 'W') + pd.to_timedelta(10, unit = 'D')

Timestamp('2026-05-10 20:32:43.210994')