# Practice Day 5

##### Titanic survivors — joins & merging
##### pd.merge, UNION, multi-table analysis
##### Q1 Load class_name.xlsx. INNER JOIN it to titanic.csv on Pclass = Pclass_number. Verify no rows were lost.
##### Q2 After joining, calculate survival rate (% survived) per ClassName. Which class had the best survival rate?
##### Q3 Split the Titanic data into two DataFrames: survivors (Survived=1) and non-survivors (Survived=0). UNION ALL them back with a new "outcome" label column.
##### Q4 Using the joined data, find average Fare paid per ClassName and Sex combination.
##### Q5 LEFT JOIN class_name.xlsx to titanic.csv. Check if any passengers have a Pclass with no matching ClassName. How would you handle this?

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\user\Desktop\Python1\DataSample\titanic.csv")
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Q1 Load class_name.xlsx. INNER JOIN it to titanic.csv on Pclass = Pclass_number. Verify no rows were lost.

In [4]:
class_nm = pd.read_excel(r"C:\Users\user\Desktop\Python1\DataSample\class_name.xlsx")
class_nm.head()

   Pclass_number     ClassName  TempField
0              1   First class   0.972901
1              2  Second class   0.707523
2              3   Third class   0.381333

In [9]:
df_q1 = pd.merge(df, class_nm, left_on = 'Pclass', right_on = 'Pclass_number')
df_q1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass_number,ClassName,TempField
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3,Third class,0.381333
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,First class,0.972901
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,Third class,0.381333
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,First class,0.972901
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3,Third class,0.381333

In [ ]:
# verify no rows were lost after inner join
df.shape[0] == df_q1.shape[0]

True

In [ ]:
# Q2 After joining, calculate survival rate (% survived) per ClassName. Which class had the best survival rate?

In [14]:
round((df_q1.groupby('ClassName')['Survived'].mean())*100,2) # First class has the highest survival rate

ClassName
First class     62.96
Second class    47.28
Third class     24.24
Name: Survived, dtype: float64

In [ ]:
# Q3 Split the Titanic data into two DataFrames: survivors (Survived=1) and non-survivors (Survived=0). 
# UNION ALL them back with a new "outcome" label column.

In [38]:
# split them up
survivors = df_q1[df_q1['Survived']==True].copy()
non_survivors = df_q1[df_q1['Survived']==False].copy()

In [39]:
# union all
survivors['outcome'] = 'survivors'
non_survivors['outcome'] = 'non-survivors'
df_q3 = pd.concat([survivors, non_survivors],ignore_index = True)

In [28]:
df_q3.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass_number,ClassName,TempField,outcome
0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,First class,0.972901,survivors
1,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,Third class,0.381333,survivors
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,First class,0.972901,survivors
3,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,3,Third class,0.381333,survivors
4,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2,Second class,0.707523,survivors

In [32]:
# Q4 Using the joined data, find average Fare paid per ClassName and Sex combination.
df_q1.groupby(['ClassName','Sex'])['Fare'].mean().reset_index().round(2)

      ClassName     Sex    Fare
0   First class  female  106.13
1   First class    male   67.23
2  Second class  female   21.97
3  Second class    male   19.74
4   Third class  female   16.12
5   Third class    male   12.66

In [ ]:
# Q5 LEFT JOIN class_name.xlsx to titanic.csv. 
# Check if any passengers have a Pclass with no matching ClassName. How would you handle this?

In [ ]:
# left join
df_q5 = pd.merge(df, class_nm, how = 'left', left_on = 'Pclass', right_on = 'Pclass_number')
df_q5.shape[0]

891

In [37]:
# pull records with ClassName equal null
df_q5['ClassName'].isna().sum()

np.int64(0)

In [ ]:
# If there were unmatched rows, options include:
# 1. Fill with a default: df_q5['ClassName'].fillna('Unknown')
# 2. Drop them: df_q5.dropna(subset=['ClassName'])
# 3. Investigate: df_q5[df_q5['ClassName'].isna()]['Pclass'].unique()