# Practice Day 8

##### Salaries — window functions & running totals
##### LAG/LEAD, running totals, rank within group, YoY growth

##### Q1 For each Year, calculate the cumulative total payroll (running total of TotalPay ordered by Year). Show the year-by-year progression.
##### Q2 Calculate year-over-year change in average TotalPay using shift(). Which year had the biggest salary jump?
##### Q3 Rank employees within each JobTitle by TotalPay (highest = rank 1). Find the top earner in each job title.
##### Q4 Add a column showing each employee's pay as a % of their JobTitle's total payroll (percent of total within group).
##### Q5 Find employees whose TotalPay increased year over year (hint: use groupby + shift on EmployeeName sorted by Year).

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\user\Desktop\Python1\DataSample\salaries.csv")
display(df.head())

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [83]:
pd.options.display.float_format = "{:.2f}".format

In [84]:
# Q1 For each Year, calculate the cumulative total payroll (running total of TotalPay ordered by Year). 
# Show the year-by-year progression.

In [85]:
df_q1 = df.groupby('Year')['TotalPay'].sum().reset_index()
df_q1['Running TotalPay'] =  df_q1['TotalPay'].cumsum()
df_q1

   Year      TotalPay  Running TotalPay
0  2011 2594195051.88     2594195051.88
1  2012 2724848200.44     5319043252.32
2  2013 2918655930.80     8237699183.12
3  2014 2876910951.26    11114610134.38

In [86]:
# Q2 Calculate year-over-year change in average TotalPay using shift(). 
# Which year had the biggest salary jump?

In [4]:
# Show the year-by-year progression.
df_q2 = df.groupby('Year')['TotalPay'].mean().reset_index()
df_q2.rename(columns = {'TotalPay':'AvgPay'}, inplace = True)
df_q2['Prev AvgPay'] = df_q2['AvgPay'].shift(1)
df_q2['yoy growth pct'] = (df_q2['AvgPay'] / df_q2['Prev AvgPay'] - 1) * 100
df_q2

   Year        AvgPay   Prev AvgPay  yoy growth pct
0  2011  71744.103871           NaN             NaN
1  2012  74113.262265  71744.103871        3.302234
2  2013  77611.443142  74113.262265        4.720047
3  2014  75463.918140  77611.443142       -2.767021

In [9]:
df_q2['Pct change'] = (df_q2['AvgPay'].pct_change())*100
df_q2

   Year        AvgPay   Prev AvgPay  yoy growth pct  Pct change
0  2011  71744.103871           NaN             NaN         NaN
1  2012  74113.262265  71744.103871        3.302234    3.302234
2  2013  77611.443142  74113.262265        4.720047    4.720047
3  2014  75463.918140  77611.443142       -2.767021   -2.767021

In [88]:
print('Year had the biggest salary jump:', df_q1.nlargest(1,'yoy growth pct')['Year'].to_string(index=False))

Year had the biggest salary jump: 2013

In [89]:
# Q3 Rank employees within each JobTitle by TotalPay (highest = rank 1). 
# Find the top earner in each job title.

In [90]:
df['Rank by JobTitle'] = df.groupby('JobTitle')['TotalPay'].rank(method='min', ascending = False).astype(int)
df.sample(5)
df[df['Rank by JobTitle']==1].sort_values(by='JobTitle')

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status,Rank by JobTitle
20765,20766,NAPOLEON VIRAY,ACCOUNT CLERK,60838.20,0.00,0.00,NaN,60838.20,60838.20,2011,NaN,San Francisco,NaN,1
19263,19264,CARLITO NEPACENA,ACCOUNTANT,65392.01,0.00,0.00,NaN,65392.01,65392.01,2011,NaN,San Francisco,NaN,1
21535,21536,PENG HUANG,ACCOUNTANT INTERN,58501.72,0.00,297.81,NaN,58799.53,58799.53,2011,NaN,San Francisco,NaN,1
135283,135284,Palminder K Hernandez,"ACPO,JuvP, Juv Prob (SFERS)",62290.78,0.00,0.00,17975.59,62290.78,80266.37,2014,NaN,San Francisco,NaN,1
18378,18379,WEN XU,ACUPUNCTURIST,66374.40,0.00,1220.00,NaN,67594.40,67594.40,2011,NaN,San Francisco,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12939,12940,DELBERT LEE,X-RAY LABORATORY AIDE,59969.74,23016.22,2091.44,NaN,85077.40,85077.40,2011,NaN,San Francisco,NaN,1
122672,122673,Omar Enzio A Lola,X-Ray Laboratory Aide,65699.00,29239.96,4874.01,29231.19,99812.97,129044.16,2014,NaN,San Francisco,NaN,1
23391,23392,MARIO YEDIDIA,"YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS",52609.91,0.00,1022.96,NaN,53632.87,53632.87,2011,NaN,San Francisco,NaN,1
58842,58843,Mario Yedidia,Youth Comm Advisor,57544.73,0.00,0.00,28229.66,57544.73,85774.39,2012,NaN,San Francisco,NaN,1
18778,18779,MYRON SULAK,ZOO CURATOR,43148.00,0.00,23538.56,NaN,66686.56,66686.56,2011,NaN,San Francisco,NaN,1

In [91]:
df.groupby('JobTitle').apply(lambda x: x.nlargest(1,'TotalPay'),include_groups=False)

,,Id,EmployeeName,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status,Rank by JobTitle
JobTitle,,,,,,,,,,,,,,
ACCOUNT CLERK,20765,20766,NAPOLEON VIRAY,60838.20,0.00,0.00,NaN,60838.20,60838.20,2011,NaN,San Francisco,NaN,1
ACCOUNTANT,19263,19264,CARLITO NEPACENA,65392.01,0.00,0.00,NaN,65392.01,65392.01,2011,NaN,San Francisco,NaN,1
ACCOUNTANT INTERN,21535,21536,PENG HUANG,58501.72,0.00,297.81,NaN,58799.53,58799.53,2011,NaN,San Francisco,NaN,1
"ACPO,JuvP, Juv Prob (SFERS)",135283,135284,Palminder K Hernandez,62290.78,0.00,0.00,17975.59,62290.78,80266.37,2014,NaN,San Francisco,NaN,1
ACUPUNCTURIST,18378,18379,WEN XU,66374.40,0.00,1220.00,NaN,67594.40,67594.40,2011,NaN,San Francisco,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
X-RAY LABORATORY AIDE,12939,12940,DELBERT LEE,59969.74,23016.22,2091.44,NaN,85077.40,85077.40,2011,NaN,San Francisco,NaN,1
X-Ray Laboratory Aide,122672,122673,Omar Enzio A Lola,65699.00,29239.96,4874.01,29231.19,99812.97,129044.16,2014,NaN,San Francisco,NaN,1
"YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS",23391,23392,MARIO YEDIDIA,52609.91,0.00,1022.96,NaN,53632.87,53632.87,2011,NaN,San Francisco,NaN,1
Youth Comm Advisor,58842,58843,Mario Yedidia,57544.73,0.00,0.00,28229.66,57544.73,85774.39,2012,NaN,San Francisco,NaN,1
ZOO CURATOR,18778,18779,MYRON SULAK,43148.00,0.00,23538.56,NaN,66686.56,66686.56,2011,NaN,San Francisco,NaN,1

In [92]:
# Q4 Add a column showing each employee's pay as a % of their JobTitle's total payroll (percent of total within group).

In [95]:
df['Pct of JobTitle Group'] = (df['TotalPay'] / df.groupby('JobTitle')['TotalPay'].transform('sum'))*100
df.sample(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status,Rank by JobTitle,Pct of JobTitle Group
13543,13544,CARLOS RUIZ,SENIOR DISTRICT ATTORNEY'S INVESTIGATOR,57571.20,2626.21,22871.56,NaN,83068.97,83068.97,2011,NaN,San Francisco,NaN,6,12.97
103655,103656,Su Zhen Lin,Porter,21625.26,0.00,629.18,222.55,22254.44,22476.99,2013,NaN,San Francisco,NaN,860,0.05
44670,44671,Stephen Solnit,IS Business Analyst-Senior,102466.03,0.00,4373.96,40207.57,106839.99,147047.56,2012,NaN,San Francisco,NaN,98,0.45
79669,79670,Aleda G Graham,Manager I,117910.21,0.00,0.00,44884.93,117910.21,162795.14,2013,NaN,San Francisco,NaN,70,0.30
80313,80314,Corey M Caballero,Registered Nurse,110306.29,2308.26,9205.57,36084.20,121820.12,157904.32,2013,NaN,San Francisco,NaN,2048,0.03
11787,11788,CORAZON ESTIVA,MENTAL HEALTH REHABILITATION WORKER,60193.00,28849.88,874.00,NaN,89916.88,89916.88,2011,NaN,San Francisco,NaN,13,0.33
126670,126671,Dennis C Guintu,Transit Operator,66525.98,6186.75,2322.84,35833.31,75035.57,110868.88,2014,NaN,San Francisco,NaN,3111,0.02
122376,122377,Lydia C Oosterbaan-Ball,Sheet Metal Worker,93999.70,782.04,1327.00,34118.89,96108.74,130227.63,2014,NaN,San Francisco,NaN,50,1.22
123514,123515,Brian V Dresser,Firefighter,72383.25,11210.82,6682.65,34541.88,90276.72,124818.60,2014,NaN,San Francisco,NaN,2118,0.03
131473,131474,Lloyd Arcega,Senior Account Clerk,65585.40,0.00,0.00,28180.85,65585.40,93766.25,2014,NaN,San Francisco,NaN,97,0.27

In [ ]:
# Q5 Find employees whose TotalPay increased year over year (hint: use groupby + shift on EmployeeName sorted by Year).

In [127]:
df_q5 = df[['EmployeeName','Year','TotalPay']].copy()
df_q5.sample(5)

          EmployeeName  Year  TotalPay
32996  KAREN CANIZALES  2011   5930.71
52373     Ellyn Parker  2012  75666.00
54396     Melissa Jaco  2012  70616.35
78509    Edmund Y Shum  2013 132401.60
43176       Sonny West  2012 115503.75

In [144]:
df_q5 = df_q5.sort_values(['EmployeeName', 'Year'])

In [146]:
df_q5['Prev TotalPay'] = df_q5.groupby('EmployeeName')['TotalPay'].shift(1)
df_q5.head(10)

                  EmployeeName  Year  TotalPay  Prev TotalPay
29353         A BERNARD FATOOH  2011  20039.91            NaN
102843       A Bernard  Fatooh  2013  23923.62            NaN
66371         A Bernard Fatooh  2012  18500.19            NaN
140525        A Bernard Fatooh  2014  24061.35       18500.19
28469    A ELIZABETH MARCHASIN  2011  26282.86            NaN
12418            A JAMIL NIAZI  2011  87496.21            NaN
140927             A K Finizio  2014  25854.81            NaN
29448    A. JAMES ROBERTSON II  2011  19473.92            NaN
103640  A. James  Robertson Ii  2013  22601.80            NaN
66487    A. James Robertson Ii  2012  22065.71            NaN

In [147]:
df_q5[df_q5['TotalPay'] > df_q5['Prev TotalPay']]

              EmployeeName  Year  TotalPay  Prev TotalPay
140525    A Bernard Fatooh  2014  24061.35       18500.19
111631       Aaron A Foltz  2014 194886.61      193590.50
120492       Aaron B Craig  2014 104177.70       93570.19
119531   Aaron Brinkerhoff  2014 108948.78       89522.11
120084     Aaron C Laycook  2014 104807.15       38582.50
...                    ...   ...       ...            ...
129804     Zoraida Leandro  2014  70996.00       66876.50
132245          Zu Ren Mei  2014  63935.94       61062.70
133294  Zulaika W Mayfield  2014  58346.36       14226.04
134812  Zulema G Gutierrez  2014  54260.34       53645.74
134057    Zun Jin Zhang He  2014  58877.30       56763.44

[17169 rows x 4 columns]